.code
	in r0, r1
	addi r2, 0
	addi r3, 1
	ld r10, :fib
	ld r11, :skip1
	ld r12, :skip2
	call r10
	out r3, r1
	halt
; r0 is input, r1 is output
:fib
	subi r31, 8
	brgt r11, r0, r2
	clr r1
	addi r31, 8
	return
:skip1
	brgt r12, r0, r3
	clr r1
	addi r1, 1
	addi r31, 8
	return
:skip2
; first recursive call
	subi r0, 1
	call r10
	push r1
; second recursive call
	subi r0, 1
	call r10
	addi r0, 2
	pop r4
	add r1, r1, r4
	addi r31, 8
	return